package:
  name: "rainbowlog"
  version: "{{ POETRY_VERSION }}"

source:
  path: ".."

requirements:
  build:
    - python >=3.7
    - pip
    - poetry

  run:
    - "importlib-metadata >=4.11"
    - "ansicolors >=1.1"

build:
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  noarch: python