name: Publish

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Set Version
        run: poetry version $(echo ${{ github.event.release.tag_name }} | cut -d 'v' -f 2)
      - name: Build Package
        run: poetry build
      - name: Check Build
        run: pip install dist/*.whl
      - name: Set POETRY_VERSION environment variable
        run: echo "POETRY_VERSION=$(poetry version -s)" >> $GITHUB_ENV
      - name: Publish Pip Package
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
